export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";

export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_ADDRESS = "SET_ADDRESS";
export const CLEAR_ADDRESS = "CLEAR_ADDRESS"
export const SET_IS_DELIVERY = "SET_IS_DELIVERY"

export const SET_BUSINESS_ADDRESS = "SET_BUSINESS_ADDRESS"